PE2: Update the uninstaller
The uninstaller got updated to handle cron jobs, so we're updating the file and
instructions accordingly.

diff --git a/source/pe/2.0/files/puppet-enterprise-uninstaller b/source/pe/2.0/files/puppet-enterprise-uninstaller
--- a/source/pe/2.0/files/puppet-enterprise-uninstaller
+++ b/source/pe/2.0/files/puppet-enterprise-uninstaller
@@ -1,17 +1,19 @@
 #!/bin/bash
 
-# Source: commit e6fa1e91d8
+# Source: commit 39d70cd5311e3e6d769affc52035a94ca728a1cc
 
 #===[ Variables ]=======================================================
 
 # Variables that hold lists of dirs, files, users, services to kill/remove
 t_pe_uninstall_dirs="/opt/puppet /var/opt/lib/pe-puppet /var/opt/lib/pe-puppetmaster /var/opt/cache/pe-puppet-dashboard /var/opt/puppet /var/log/pe-*"
 t_pe_purge_dirs="/etc/puppetlabs"
-t_pe_files="/etc/init.d/pe-*"
+t_pe_files="/etc/init.d/pe-* /var/run/pe-*/* /var/run/pe-* /var/lock/subsys/pe-* /var/lock/pe-*"
 t_pe_processes="puppetagent pe-puppet pe-puppet-agent pe-mcollective pe-httpd pe-activemq pe-memcached pe-dashboard-workers"
 t_pe_users_and_groups="pe-memcached pe-apache pe-puppet puppet-dashboard pe-activemq peadmin pe-mco"
 t_pe_packages_to_check='^pe-.*$'
 t_pe_symlinks="puppet facter puppet-module mco pe-man"
+t_pe_cronjobs="report_baseline pe-mcollective-metadata"
+t_pe_crond_files="default-add-all-nodes"
 
 #===[ Functions ]=======================================================
 
@@ -23,24 +25,31 @@ display_uninstall_usage() {
     t_display_usage__error="${1:-""}"
 
     display "
-USAGE: $(basename "${0?}") [-p] [-n] [-d] [-y]
+USAGE: $(basename "${0?}") [-a ANSWER_FILE] [-A ANSWER_FILE] [-d] [-h] [-n] [-p] [-s ANSWER_FILE] [-y]
 
 OPTIONS:
+    -a ANSWER_FILE
+        Read answers from file and quit with error if an answer is missing.
+    -A ANSWER_FILE
+        Read answers from file and prompt for input if an answer is missing.
+    -d
+        Also remove any databases during the uninstall.
+    -h
+        Display this help screen
+    -n
+        Run in 'noop' mode; show commands that would have been run
+        during installation without running them.
     -p
         Perform a 'purge', a full uninstall of Puppet Enterprise. Remove
         all configuration files and user home directories in addition
         to the standard uninstall.
-    -n
-        Run in 'noop' mode; show commands that would have been run
-        during installation without running them.
-    -d
-        Also remove any databases during the uninstall.
-
+    -s ANSWER_FILE
+        Save answers to file and quit without uninstalling.
     -y
         Assume yes to 'Are you sure?'
 "
 
-    if [ ! -z "${t_display_usage__error?}" ]; then
+    if [ -n "${t_display_usage__error?}" ]; then
         display_newline
         display_failure "${t_display_usage__error?}"
     else
@@ -53,8 +62,26 @@ OPTIONS:
 
 handle_process() {
   case "${1?}" in
-    pe-puppet|pe-puppet-agent|puppetagent)
-      PROC="-f /opt/puppet/bin/puppet"
+    pe-puppet)
+      if [ "$PLATFORM_NAME" = "debian" ] || [ "$PLATFORM_NAME" = "ubuntu" ]; then
+        PROC="-f /opt/puppet/bin/puppet"
+      else
+        return 0
+      fi
+    ;;
+    pe-puppet-agent)
+      if [ "$PLATFORM_NAME" = "el" ] || [ "$PLATFORM_NAME" = "sles" ]; then
+        PROC="-f /opt/puppet/bin/puppet"
+      else
+        return 0
+      fi
+    ;;
+    puppetagent)
+      if [ "$PLATFORM_NAME" = "solaris" ]; then
+        PROC="-f /opt/puppet/bin/puppet"
+      else
+        return 0
+      fi
     ;;
 
     pe-httpd)
@@ -90,10 +117,10 @@ handle_process() {
     if (! stop_process ${1?}) || (pgrep $PROC &> /dev/null) || (ps -ef | $PLATFORM_EGREP 'delayed_job\.[[:digit:]]*_monitor' &> /dev/null); then
       PID="$(pgrep $PROC) $(ps -ef | $PLATFORM_EGREP 'delayed_job\.[[:digit:]]*_monitor' | awk '{ print $2 }' | xargs)"
       PIDS=$(echo ${PID} | tr -d "\n")
-      if ! [ -z "${PIDS}" ]; then
+      if [ -n "${PIDS}" ]; then
         for sig in "TERM" "KILL"; do
           run "kill -${sig} ${PIDS?}"
-          sleep 5
+          sleep 3
           PID="$(pgrep $PROC) $(ps -ef | $PLATFORM_EGREP 'delayed_job\.[[:digit:]]*_monitor' | awk '{ print $2 }' | xargs)"
           PIDS=$(echo ${PID} | tr -d "\n")
           # Break out if there are no PIDs remaining to kill or if they are gone (aren't responding to signals, via kill -0)
@@ -148,7 +175,7 @@ stop_process() {
 kill_process() {
   PID=$(pgrep ${1?} | xargs)
   PIDS=$(echo ${PID} | tr -d "\n")
-  if ! [ -z "$PIDS" ]; then
+  if [ -n "$PIDS" ]; then
     for sig in "TERM" "KILL"; do
       run "kill -${sig} ${PIDS?}"
       sleep 5
@@ -207,14 +234,19 @@ remove_pe_packages() {
     rpm)
       packages_to_remove="$(rpm -qa | ${PLATFORM_EGREP?} ${t_pe_packages_to_check?} | xargs)"
       command_to_remove_packages="rpm -e --allmatches ${packages_to_remove?}"
-      if [ ! -z "${packages_to_remove?}" ]; then
+      if [ -n "${packages_to_remove?}" ]; then
         run "${command_to_remove_packages?}"
       fi
     ;;
     dpkg)
       packages_to_remove="$(dpkg-query --show --showformat '${Package}\n' | ${PLATFORM_EGREP?} ${t_pe_packages_to_check?} | xargs)"
-      command_to_remove_packages="dpkg -P ${packages_to_remove?}"
-      if [ ! -z "${packages_to_remove?}" ]; then
+      if is_purge; then
+        command_to_remove_packages="dpkg -P ${packages_to_remove?}"
+      else
+        command_to_remove_packages="dpkg -r ${packages_to_remove?}"
+      fi
+
+      if [ -n "${packages_to_remove?}" ]; then
         run "${command_to_remove_packages?}"
       fi
     ;;
@@ -231,9 +263,25 @@ remove_pe_packages() {
   esac
 }
 
+#...[ Remove crons ]..........................................................
+
+remove_cron() {
+  # First remove the cron resources if they exist
+  for cron in $t_pe_cronjobs; do
+    if run "/opt/puppet/bin/puppet resource cron | ${PLATFORM_EGREP?} ${cron?}" &> /dev/null; then
+      run "/opt/puppet/bin/puppet resource cron '${cron?}' ensure=absent"
+    fi
+  done
+
+  # Next remove our job(s) in /etc/cron.d if it exists
+  for cron in $t_pe_crond_files; do
+    [ -f /etc/cron.d/${cron?} ] && run "rm -rf '/etc/cron.d/${cron?}'"
+  done
+}
+
 get_db_field() {
   # Grabs the passed field out of the database config file for the console, if the field exists.
-  sed -n "s/^\s*${1?}: \(.*\)\s*$/\1/p" /etc/puppetlabs/puppet-dashboard/database.yml | head -n 1
+  sed -n "s/^\s*${1?}:\s*\(.*\)\s*$/\1/p" /etc/puppetlabs/puppet-dashboard/database.yml | head -n 1
 }
 
 fail() {
@@ -253,7 +301,7 @@ stop_pe_processes() {
 }
 
 is_purge() {
-  if [ y = "${IS_PURGE:-""}" ]; then
+  if [ y = "${q_pe_purge:-""}" ]; then
     return 0
   else
     return 1
@@ -261,7 +309,7 @@ is_purge() {
 }
 
 is_remove_db() {
-  if [ y = "${REMOVE_DB:-""}" ]; then
+  if [ y = "${q_pe_remove_db:-""}" ]; then
     return 0
   else
     return 1
@@ -287,18 +335,44 @@ prepare_user
 IS_DEBUG=n
 IS_NOOP=n
 IS_PURGE=n
+ANSWER_FILE_TO_LOAD=
+ANSWER_FILE_TO_SAVE=
+IS_ANSWER_REQUIRED=n
 
-while getopts npdy option; do
+if [ -z "$PLATFORM_EGREP" ]; then
+  if [ ${PLATFORM_NAME?} = "solaris" ]; then
+    PLATFORM_EGREP='egrep'
+  else
+    PLATFORM_EGREP='grep -E'
+  fi
+fi
+
+while getopts a:A:dhnps:y option; do
   case "$option" in
+    a)
+      ANSWER_FILE_TO_LOAD="${OPTARG?}"
+      IS_ANSWER_REQUIRED=y
+    ;;
+    A)
+      ANSWER_FILE_TO_LOAD="${OPTARG?}"
+      IS_ANSWER_REQUIRED=n
+    ;;
+    d)
+      q_pe_remove_db=y
+    ;;
+    h)
+      display_header
+      display_uninstall_usage
+    ;;
     n)
       IS_NOOP=y
       IS_DEBUG=y
     ;;
-    d)
-      REMOVE_DB=y
-    ;;
     p)
-      IS_PURGE=y
+      q_pe_purge=y
+    ;;
+    s)
+      ANSWER_FILE_TO_SAVE="${OPTARG?}"
     ;;
     y)
       q_pe_uninstall=y
@@ -310,18 +384,30 @@ while getopts npdy option; do
   esac
 done
 
+# Load answers if specified:
+if [ -n "${ANSWER_FILE_TO_LOAD?}" ]; then
+  load_answers "${ANSWER_FILE_TO_LOAD?}"
+fi
+
 # Setup
 display_major_separator
 display_newline
 display "Puppet Enterprise v$(cat "$(installer_dir)/VERSION") uninstaller"
 display_newline
 
+if is_remove_db; then
+  if [ -z "$q_pe_db_root_pass" ]; then
+    display "In order to remove your console database user, we need to know the root password for mysql."
+    ask q_pe_db_root_pass "What password does the 'root' user have on the database server?" StringOrBlank ""
+  fi
+fi
+
 # Display the flags passed
 display "Options selected:"
 if is_purge; then
   display '* Purge: Full uninstall'
 else
-  display '* Partial uninstall (leave configuration files and homedirs)'
+  display '* Partial uninstall (leave most configuration files and homedirs)'
 fi
 
 if is_remove_db; then
@@ -333,9 +419,23 @@ if is_noop; then
 fi
 
 display_newline
+display_major_separator
+display_newline
 
 # Make sure this is what they want.
+if is_package_installed 'pe-puppet-dashboard' && ! is_remove_db; then
+  display "*** Warning: The uninstall will remove your console database configuration files and you have selected to not remove the console databases."
+  display_newline
+  display_major_separator
+  display_newline
+fi
+
 ask q_pe_uninstall 'Uninstall Puppet Enterprise?' yN
+
+if [ -n "${ANSWER_FILE_TO_SAVE?}" ]; then
+  set | ${PLATFORM_EGREP?} '^q_pe_' > ${ANSWER_FILE_TO_SAVE?}
+  quit
+fi
 
 if [ ! y = "${q_pe_uninstall?}" ]; then
   display_newline
@@ -347,6 +447,13 @@ if [ ! y = "${q_pe_uninstall?}" ]; then
   quit
 fi
 
+display_newline
+display_major_separator
+display_newline
+
+# Remove PE cronjobs
+status "Removing PE cronjobs..."
+remove_cron
 
 # Remove PE packages
 # First stop the processes
@@ -356,6 +463,12 @@ stop_pe_processes
 # Remove Console DB
 if is_remove_db; then
   status "Removing PE database(s)..."
+  if ! which mysql &> /dev/null; then
+    fail "Could not drop databases, could not find mysql."
+  else
+    t_mysql=$(which mysql)
+  fi
+
   if [ -e /etc/puppetlabs/puppet-dashboard/database.yml ]; then
     # Get the DB name, user, passwd
     t_pe_db_name=$(get_db_field database)
@@ -364,7 +477,30 @@ if is_remove_db; then
   else
     fail "Could not drop databases, there is no database information available for the console."
   fi
-  run "mysql -u ${t_pe_db_user?} -p${t_pe_db_passwd} -e 'drop database ${t_pe_db_name}; drop database ${t_pe_db_name}_inventory_service'"
+
+  if [ -z "$t_pe_db_name" -o -z "$t_pe_db_user" ]; then
+    fail "Could not drop databases, bad credentials in /etc/puppetlabs/puppet-dashboard/database.yml"
+  else
+    if [ -n "$t_pe_db_passwd" ]; then
+      t_pass_string="-p${t_pe_db_passwd}"
+    fi
+
+    if eval "${t_mysql?} -u ${t_pe_db_user?} ${t_pass_string} ${t_pe_db_name?} -e 'SHOW TABLES'" &> /dev/null; then
+      run "${t_mysql?} -u ${t_pe_db_user?} ${t_pass_string} -e 'DROP DATABASE ${t_pe_db_name}'"
+    fi
+
+    if eval "${t_mysql?} -u ${t_pe_db_user?} ${t_pass_string} ${t_pe_db_name?}_inventory_service -e 'SHOW TABLES'" &> /dev/null; then
+      run "${t_mysql?} -u ${t_pe_db_user?} ${t_pass_string} -e 'DROP DATABASE ${t_pe_db_name}_inventory_service'"
+    fi
+
+    if [ -n "$q_pe_db_root_pass" ]; then
+      t_root_pass_string="-p${q_pe_db_root_pass}"
+    fi
+
+    if eval "${t_mysql?} -u root ${t_root_pass_string} mysql -e \"SELECT * FROM user WHERE User='${t_pe_db_user?}' AND Host='localhost'\"" &> /dev/null; then
+      run "${t_mysql?} -u root ${t_root_pass_string} -e 'DROP USER \"${t_pe_db_user?}\"@\"localhost\"'"
+    fi
+  fi
 fi
 
 # Then remove the packages
@@ -393,9 +529,9 @@ else
   t_dirs_files_to_delete="$t_pe_uninstall_dirs $t_pe_files"
 fi
 
-for dir in $t_dirs_files_to_delete; do
-  if ! [ -z $dir ]; then
-    run "rm -rf ${dir}"
+for entry in $t_dirs_files_to_delete; do
+  if [ -n "$entry" -a -e "$entry" ]; then
+    run "rm -rf '${entry}'"
   fi
 done
 
